### PR TITLE
Added console input/output replacement

### PR DESCRIPTION
**Pull request by sbarisic**

### CODE REVIEW

**Comment by Rohansi** [comment]
You know you could have just added a reference to [Texter](https://github.com/Rohansi/Texter), right?

**Comment by sbarisic** [comment]
I could have yes, but i don't want to use texter. I'm just using it as a reference to write my own one. Oh and i borrowed your shaders temporarily.

**Comment by Metapyziks** [comment]
I think you've missed out the sfmlnet-xxxx-2 DLLs.

**Comment by Metapyziks** [comment]
@Rohansi Texter does look perfect for this.

**Comment by dajoh** [comment]
@cartman300 You're actually breaking the law by using Texter without permission.

**Comment by Metapyziks** [comment]
As of 40 minutes ago at least, although I'm not sure how it works when it was unlicensed.

**Comment by dajoh** [comment]
Still not compliant with the license terms.

**Comment by sbarisic** [comment]
I am not using Texter, and now i even won't. In fact i'll strip off every single bit of everything that reminds me of it. The only thing i actually copypasted are the shaders because i wanted a quick working version so i can complete the input without being arsed to write my own (that is, the output).

**Comment by Rohansi** [comment]
You copied (and slightly changed) the TextDisplay class too. It's probably best to just use Texter instead of your crippled copy of it.

**Comment by sbarisic** [comment]
Okay.

**Comment by Metapyziks** [comment]
Your reorganisation of the script location and bin directory are useful though, so perhaps just include those and reference Texter (with its license included) with your input fixes as your pull request.

**Comment by sbarisic** [comment]
Texter is bugged, it doesn't support transparency, it doesn't support proper text character colors (gray stays gray, it doesn't get colored). I will, in fact, strip off whole SFML and use SDL instead.

**Comment by dajoh** [comment]
If you decide to modify Texter, provide proper credit & the copyright notice of the original author.

**Comment by Tamschi** [comment]
Yes, it's pretty important to not have liabilities floating around in the version history either.
If there are any it would be a very good idea to fold the commits before making a pull request.

**Comment by Rohansi** [comment]
@cartman300 I just fixed those issues. Feel free to use it (properly, this time) when you're done fiddling with SDL.

**Pull request closed without merging**
